# Generated by Django 5.2 on 2025-04-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankorgapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='account_type',
            field=models.CharField(choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current'), ('LOAN', 'Loan')], max_length=16),
        ),
    ]
