# Generated by Django 5.2 on 2025-04-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankorgapp', '0003_alter_myuser_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account_no', models.CharField(max_length=16)),
                ('to_account_no', models.CharField(max_length=16)),
                ('amount', models.FloatField()),
                ('note', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
